### ISSUE TITLE
`IdiomMatcher` - show decoded  results along with the matched results 

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/identify-idioms#16]
## Why?
정확히 어떤 idioms을 identify했는지 알려주기 위해선, decoded된 결과도 보여주는 것이 필요할 것.
기왕 이렇게 된거.. 아예 json으로 다 보여주자.

## To-do's
- [x] `identify` 함수 추가하기
- [x] 리드미 정리하기!  모든 케이스 별로  데모를 보여주기.
- [x] 리드미 - table로 깔끔하게 보여주기
- [x] 리드미 - leaving no stones unturned  논문 인용하기
- [x] 리드미 - adding idioms yourself - instruction도 작성하기

**Comment by eubinecto** [comment]
## Readme 정리하기
이제 무엇을 해야할까? 다른 이름으로 바꾸는 것? 아.. 뭔가 단어 하나로 모든 것을 표현하고 싶다.
하지만 지금 그게 떠오르지는 않는다. 일단 그대로 이어가자. 핵심을 제대로 표현하는게 나을 것.

지금으로서는.. 일단 테이블로 모든 케이스를 정리해보자.
