### ISSUE TITLE
The lemmas of idioms should not contain whitespaces

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/identify-idioms#9]
## The problem

As of right now, the lemmatised string of idioms contains whitespaces (except the hyphenated ones) like so:
```
tokenisation: ['You', 'are', 'down to earth', '.']
lemmatisation: ['you', 'be', 'down-to-earth', '.']
filtering: ['down-to-earth']
-----------
tokenisation: ['Have', 'you', 'found your feet', 'on', 'the', 'new', 'job', '?']
lemmatisation: ['have', 'you', "find one's feet", 'on', 'the', 'new', 'job', '?']
filtering: ["find one's feet"]
```

This may cause some problems when the tokens are serialised into a whitespace-delimeted file (e.g. KeyedVectors ).

## Objective
All the whitespaces in the lemmas must be replaced with an underbar.
e.g.
before | after
--- | ---
 "find one's feet" | "find_one's_feet"

## To-do's
- [x] simplify the loaders
- [x]  refactor the `scripts` 
- [x] replace the whitspaces with underbar on loading the idioms

**Comment by eubinecto** [comment]
## How should I approach this then?

Just replace the whitspaces with an under bar **on loading the idioms**.
